import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-indigo/theme.css';  
import 'primeflex/primeflex.css';                                 
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.css';  

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dair',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <PrimeReactProvider>
      <body className={inter.className}>
        {children}
      </body>
      </PrimeReactProvider>
    </html>
  )
}
